---
version: 0.2

phases:
   build:
      commands:
         - >-
            cd
            "${CODEBUILD_SRC_DIR_sources}"
         - >-
            sh
            -x
            --
            build.sh

artifacts:
   base-directory: output
   files:
      - '**/*'
