---
AWSTemplateFormatVersion: 2010-09-09


Description: Foothold for webpipe source integrations.


Metadata:
   AWS::CloudFormation::Interface:
      ParameterGroups:
         -
            Label: General
            Parameters:
               - IntegrationAccountId
         -
            Label: Customer
            Parameters:
               - CustomerToken

      ParameterLabels:
         CustomerToken:
            default: Token
         IntegrationAccountId:
            default: AWS account


Parameters:
   CustomerToken:
      Description: Token assigned to you by the webpipe source integration.
      Type: String
      NoEcho: true

   IntegrationAccountId:
      Description: ID of the AWS account that hosts the webpipe source integration.
      Type: String
      AllowedPattern: '^\d{12}$'
      MinLength: 12
      MaxLength: 12
      ConstraintDescription: must be a valid AWS account ID


Resources:
   # webline deploys a CloudFormation stack.
   # The stack might contain IAM roles.
   # If it creates IAM roles with wide permissions, we have privilege escalation.
   # Thus, we only let CloudFormation create roles
   # if they have a permissions boundary (the policy below).
   PermissionsBoundary:
      Type: AWS::IAM::ManagedPolicy
      Properties: {
         Description: 'Permissions boundary for IAM roles of webpipe pipelines.',
         PolicyDocument: {
            Version: 2012-10-17,
            Statement: [
               {
                  # Pipelines shouldn't need to use some services (listed below)
                  Sid: restrict,
                  Action: [
                     'aws-portal:*',
                     'ec2:*',
                     'iam:*',
                  ],
                  Resource: '*',
                  Effect: Deny,
               },
            ],
         },
      }

   AppRole:
      Type: AWS::IAM::Role
      Properties: {
         Path: /webpipe/foothold/,
         AssumeRolePolicyDocument: {
            Version: 2012-10-17,
            Statement: [
               {
                  Principal: {
                     AWS: {
                        Ref: IntegrationAccountId,
                     },
                  },
                  Action: [
                     'sts:AssumeRole',
                  ],
                  Condition: {
                     StringEquals: {
                        'sts:ExternalId': {
                           Ref: CustomerToken,
                        },
                     },
                  },
                  Effect: Allow,
               },
            ],
         },
         Policies: [
            {
               PolicyName: pipeline-deployment,
               PolicyDocument: {
                  Version: 2012-10-17,
                  Statement: [
                     {
                        Action: [
                           'cloudformation:CreateStack',
                           'cloudformation:DeleteStack',
                           'cloudformation:DescribeStacks',
                           'cloudformation:UpdateStack',
                        ],
                        Resource: [
                           {
                              'Fn::Sub': 'arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/webpipe-pipeline-*/*',
                           },
                        ],
                        Effect: Allow,
                     },
                     {
                        Action: [
                           'iam:PassRole',
                        ],
                        Resource: [
                           {
                              'Fn::GetAtt': [
                                 CloudFormationRole,
                                 Arn,
                              ],
                           },
                        ],
                        Condition: {
                           StringEquals: {
                              'iam:PassedToService': {
                                 Fn::Sub: 'cloudformation.${AWS::URLSuffix}',
                              },
                           },
                        },
                        Effect: Allow,
                     },
                  ],
               },
            },
            {
               PolicyName: pipeline-feed,
               PolicyDocument: {
                  Version: 2012-10-17,
                  Statement: [
                     {
                        Action: [
                           's3:DeleteObject',
                           's3:PutObject',
                        ],
                        Resource: [
                           {
                              'Fn::Sub': '${BridgeBucket.Arn}/*',
                           },
                        ],
                        Effect: Allow,
                     },
                  ],
               },
            },
            {
               PolicyName: pipeline-control,
               PolicyDocument: {
                  Version: 2012-10-17,
                  Statement: [
                     {
                        Action: [
                           'codepipeline:StartPipelineExecution',
                        ],
                        Resource: [
                           {
                              'Fn::Sub': 'arn:${AWS::Partition}:codepipeline:*:${AWS::AccountId}:webpipe*',
                           },
                        ],
                        Effect: Allow,
                     },
                  ],
               },
            },
         ],
      }

   # This IAM role lets CloudFormation create and delete
   # the webpipe pipeline stack.
   CloudFormationRole:
      Type: AWS::IAM::Role
      Properties: {
         Path: /webpipe/foothold/,
         AssumeRolePolicyDocument: {
            Version: 2012-10-17,
            Statement: [
               {
                  Principal: {
                     Service: [
                        {
                           'Fn::Sub': 'cloudformation.${AWS::URLSuffix}',
                        },
                     ],
                  },
                  Action: [
                     'sts:AssumeRole',
                  ],
                  Effect: Allow,
               },
            ],
         },
         Policies: [
            {
               PolicyName: management,
               PolicyDocument: {
                  Version: 2012-10-17,
                  Statement: [
                     {
                        Sid: codepipeline,
                        Action: [
                           'codepipeline:CreatePipeline',
                           'codepipeline:DeletePipeline',
                        ],
                        Resource: [
                           {
                              'Fn::Sub': 'arn:${AWS::Partition}:codepipeline:*:${AWS::AccountId}:webpipe*',
                           },
                        ],
                        Effect: Allow,
                     },
                     {
                        Sid: codebuild,
                        Action: [
                           'codebuild:CreateProject',
                        ],
                        Resource: [
                           {
                              'Fn::Sub': 'arn:${AWS::Partition}:codepipeline:*:${AWS::AccountId}:webpipe*',
                           },
                        ],
                        Effect: Allow,
                     },
                     {
                        # IAM permissions that may be restricted
                        # by permission boundaries
                        Sid: iam-bounded,
                        Action: [
                           'iam:AttachRolePolicy',
                           'iam:CreateRole',
                           'iam:DeleteRolePolicy',
                           'iam:DetachRolePolicy',
                           'iam:PutRolePolicy',
                        ],
                        Resource: [
                           {
                              'Fn::Sub': 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/webpipe/pipeline/*',
                           },
                        ],
                        Condition: {
                           StringEquals: {
                              'iam:PermissionsBoundary': {
                                 Ref: PermissionsBoundary,
                              },
                           },
                        },
                        Effect: Allow,
                     },
                     {
                        # IAM permissions that cannot be restricted
                        # by permission boundaries
                        Sid: iam-unbounded,
                        Action: [
                           'iam:DeleteRole',
                           'iam:GetRole',
                           'iam:GetRolePolicy',
                           'iam:ListAttachedRolePolicies',
                           'iam:ListRolePolicies',
                           'iam:ListRoleTags',
                           'iam:TagRole',
                           'iam:UntagRole',
                           'iam:UpdateAssumeRolePolicy',
                           'iam:UpdateRole',
                           'iam:UpdateRoleDescription',
                        ],
                        Resource: [
                           {
                              'Fn::Sub': 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/webpipe/pipeline/*',
                           },
                        ],
                        Effect: Allow,
                     },
                  ],
               },
            },
         ],
      }


Outputs:
   Role: !If
      Description: 'Name of the IAM role.'
      Value:
         Ref: Role
   RoleArn: !If
      Description: 'ARN of the IAM role.'
      Value:
         Fn::GetAtt:
            - Role
            - Arn
